//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class move
    {
        public int id { get; set; }
        public int game { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string inWhom { get; set; }
        public bool whiteMove { get; set; }
    
        public virtual game gameObject { get; set; }
    }
}
